const commandsPokechat = [
	{
		name: 'argent',
		description: 'Affiche votre argent',
	},
	{
		name: 'code-affiliation',
		description: "Affiche votre code d'affiliation",
	},
	{
		name: 'utiliser-code-affiliation',
		description: 'Utilise un code d’affiliation, donnant 10 000 pokédollars à chaque personne',
		options: [
			{
				name: 'code',
				type: 3,
				description: 'Code d’affiliation',
				required: true,
			},
		],
	},
	{
		name: 'pokedex',
		description: 'Affiche votre Pokédex ou celui d’un dresseur',
		options: [
			{
				name: 'generation',
				type: 4,
				description: 'Numéro de la génération de Pokémon',
				required: false,
			},
			{
				name: 'dresseur',
				type: 6,
				description: 'Nom du dresseur',
				required: false,
			},
		],
	},
	{
		name: 'shinydex',
		description: 'Affiche votre Shinydex ou celui d’un dresseur',
		options: [
			{
				name: 'generation',
				type: 4,
				description: 'Numéro de la génération de Pokémon',
				required: false,
			},
			{
				name: 'dresseur',
				type: 6,
				description: 'Nom du dresseur',
				required: false,
			},
		],
	},
	{
		name: 'pokedex-liste',
		description: 'Affiche la liste des vos Pokédex',
	},
	{
		name: 'shinydex-liste',
		description: 'Affiche la liste des vos Shinydex',
	},
	{
		name: 'ball',
		description: 'Affiche vos Pokéballs',
	},
	{
		name: 'cadeau',
		description: 'Ouvre un cadeau, disponible toutes les 12h',
	},
	{
		name: 'evolution',
		description: 'Fait évoluer un Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
			{
				name: 'max',
				type: 3,
				description: 'Faire évoluer le maximum de Pokémon possible',
				required: false,
				choices: [
					{ name: 'Oui', value: 'true' },
					{ name: 'Non', value: 'false' },
				],
			},
			{
				name: 'quantite',
				type: 4,
				description: 'Nombre de Pokémon à faire évoluer',
				required: false,
			},
		],
	},
	{
		name: 'evolution-shiny',
		description: 'Fait évoluer un Pokémon shiny',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
			{
				name: 'max',
				type: 3,
				description: 'Faire évoluer le maximum de Pokémon shiny possible',
				required: false,
				choices: [
					{ name: 'Oui', value: 'true' },
					{ name: 'Non', value: 'false' },
				],
			},
			{
				name: 'quantite',
				type: 4,
				description: 'Nombre de Pokémon shiny à faire évoluer',
				required: false,
			},
		],
	},
	{
		name: 'zone',
		description: 'Affiche la zone de spawn d’un Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'vendre',
		description: 'Vend un ou plusieurs Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
			{
				name: 'max',
				type: 3,
				description: 'Vendre le maximum de Pokémon possible, en laissant 1',
				required: false,
				choices: [
					{ name: 'Non', value: 'false' },
					{ name: 'Oui', value: 'true' },
				],
			},
			{
				name: 'quantite',
				type: 4,
				description: 'Quantité de Pokémon',
				required: false,
			},
		],
	},
	{
		name: 'vendre-shiny',
		description: 'Vend un ou plusieurs Pokémon shiny',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
			{
				name: 'max',
				type: 3,
				description: 'Vendre le maximum de Pokémon shiny possible, en laissant 1',
				required: false,
				choices: [
					{ name: 'Non', value: 'false' },
					{ name: 'Oui', value: 'true' },
				],
			},
			{
				name: 'quantite',
				type: 4,
				description: 'Quantité de Pokémon shiny',
				required: false,
			},
		],
	},
	{
		name: 'prix',
		description: 'Affiche le prix d’un Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'nombre-evolution',
		description: 'Affiche le nombre de Pokémon pour faire évoluer un Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon à faire évoluer',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'cherche',
		description: 'Cherche un Pokémon',
	},
	{
		name: 'canne',
		description: 'Pêche un Pokémon avec la canne',
	},
	{
		name: 'super-canne',
		description: 'Pêche un Pokémon avec la super canne',
	},
	{
		name: 'mega-canne',
		description: 'Pêche un Pokémon avec la méga canne',
	},
	{
		name: 'disponible',
		description: 'Affiche les Pokémon disponibles dans le canal',
	},
	{
		name: 'boutique',
		description: 'Ouvre la boutique de Pokéballs',
	},
	{
		name: 'quantite',
		description: 'Affiche la quantité de Pokémon que vous possédez pour un nom donné',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'quantite-shiny',
		description: 'Affiche la quantité de Pokémon shiny que vous possédez pour un nom donné',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'rune-acheter',
		description:
			"Achète une rune d'un Pokémon pour le faire apparaître (prix: 3X le prix de vente du Pokémon)",
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
			{
				name: 'quantite',
				type: 4,
				description: 'Quantité de runes de Pokémon à acheter',
				required: false,
			},
		],
	},
	{
		name: 'rune-utiliser',
		description: 'Utilise une rune de Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'rune-inventaire',
		description: 'Affiche votre inventaire de runes de Pokémon',
	},
	{
		name: 'rune-prix',
		description: 'Affiche le prix d’une rune de Pokémon',
		options: [
			{
				name: 'nom',
				type: 3,
				description: 'Nom du Pokémon',
				required: true,
				autocomplete: true,
			},
		],
	},
	{
		name: 'echange',
		description: 'Propose un échange de Pokémon',
		options: [
			{
				name: 'quantite_pokemon_propose',
				type: 4,
				description: 'Quantite de Pokemon que vous proposez',
				required: true,
			},
			{
				name: 'nom_pokemon_propose',
				type: 3,
				description: 'Nom du Pokemon que vous proposez',
				required: true,
				autocomplete: true,
			},
			{
				name: 'pokemon_propose_shiny',
				type: 3,
				description: 'Est-ce que le Pokemon que vous proposez est shiny?',
				required: true,
				choices: [
					{ name: 'Oui', value: 'true' },
					{ name: 'Non', value: 'false' },
				],
			},
			{
				name: 'quantite_pokemon_demande',
				type: 4,
				description: 'Quantite de Pokemon que vous demandez',
				required: true,
			},
			{
				name: 'nom_pokemon_demande',
				type: 3,
				description: 'Nom du Pokemon que vous demandez',
				required: true,
				autocomplete: true,
			},
			{
				name: 'pokemon_demande_shiny',
				type: 3,
				description: 'Est-ce que le Pokemon que vous demandez est shiny?',
				required: true,
				choices: [
					{ name: 'Oui', value: 'true' },
					{ name: 'Non', value: 'false' },
				],
			},
		],
	},
];

const balls = [
	{ name: 'pokeball', id: 1 },
	{ name: 'superball', id: 2 },
	{ name: 'hyperball', id: 3 },
	{ name: 'masterball', id: 4 },
];

const pokemons = [
	'Bulbizarre',
	'Herbizarre',
	'Florizarre',
	'Salamèche',
	'Reptincel',
	'Dracaufeu',
	'Carapuce',
	'Carabaffe',
	'Tortank',
	'Chenipan',
	'Chrysacier',
	'Papilusion',
	'Aspicot',
	'Coconfort',
	'Dardargnan',
	'Roucool',
	'Roucoups',
	'Roucarnage',
	'Rattata',
	'Rattatac',
	'Piafabec',
	'Rapasdepic',
	'Abo',
	'Arbok',
	'Pikachu',
	'Raichu',
	'Sabelette',
	'Sablaireau',
	'NidoranF',
	'Nidorina',
	'Nidoqueen',
	'NidoranM',
	'Nidorino',
	'Nidoking',
	'Mélofée',
	'Mélodelfe',
	'Goupix',
	'Feunard',
	'Rondoudou',
	'Grodoudou',
	'Nosferapti',
	'Nosferalto',
	'Mystherbe',
	'Ortide',
	'Rafflesia',
	'Paras',
	'Parasect',
	'Mimitoss',
	'Aéromite',
	'Taupiqueur',
	'Triopikeur',
	'Miaouss',
	'Persian',
	'Psykokwak',
	'Akwakwak',
	'Férosinge',
	'Colossinge',
	'Caninos',
	'Arcanin',
	'Ptitard',
	'Têtarte',
	'Tartard',
	'Abra',
	'Kadabra',
	'Alakazam',
	'Machoc',
	'Machopeur',
	'Mackogneur',
	'Chétiflor',
	'Boustiflor',
	'Empiflor',
	'Tentacool',
	'Tentacruel',
	'Racaillou',
	'Gravalanch',
	'Grolem',
	'Ponyta',
	'Galopa',
	'Ramoloss',
	'Flagadoss',
	'Magnéti',
	'Magnéton',
	'Canarticho',
	'Doduo',
	'Dodrio',
	'Otaria',
	'Lamantine',
	'Tadmorv',
	'Grotadmorv',
	'Kokiyas',
	'Crustabri',
	'Fantominus',
	'Spectrum',
	'Ectoplasma',
	'Onix',
	'Soporifik',
	'Hypnomade',
	'Krabby',
	'Krabboss',
	'Voltorbe',
	'Électrode',
	'Noeunoeuf',
	'Noadkoko',
	'Osselait',
	'Ossatueur',
	'Kicklee',
	'Tygnon',
	'Excelangue',
	'Smogo',
	'Smogogo',
	'Rhinocorne',
	'Rhinoféros',
	'Leveinard',
	'Saquedeneu',
	'Kangourex',
	'Hypotrempe',
	'Hypocéan',
	'Poissirène',
	'Poissoroy',
	'Stari',
	'Staross',
	'M. Mime',
	'Insécateur',
	'Lippoutou',
	'Élektek',
	'Magmar',
	'Scarabrute',
	'Tauros',
	'Magicarpe',
	'Léviator',
	'Lokhlass',
	'Métamorph',
	'Evoli',
	'Aquali',
	'Voltali',
	'Pyroli',
	'Porygon',
	'Amonita',
	'Amonistar',
	'Kabuto',
	'Kabutops',
	'Ptéra',
	'Ronflex',
	'Artikodin',
	'Électhor',
	'Sulfura',
	'Minidraco',
	'Draco',
	'Dracolosse',
	'Mewtwo',
	'Mew',
	'Germignon',
	'Macronium',
	'Méganium',
	'Héricendre',
	'Feurisson',
	'Typhlosion',
	'Kaiminus',
	'Crocrodil',
	'Aligatueur',
	'Fouinette',
	'Fouinar',
	'Hoothoot',
	'Noarfang',
	'Coxy',
	'Coxyclaque',
	'Mimigal',
	'Migalos',
	'Nostenfer',
	'Loupio',
	'Lanturn',
	'Pichu',
	'Mélo',
	'Toudoudou',
	'Togepi',
	'Togetic',
	'Natu',
	'Xatu',
	'Wattouat',
	'Lainergie',
	'Pharamp',
	'Joliflor',
	'Marill',
	'Azumarill',
	'Simularbre',
	'Tarpaud',
	'Granivol',
	'Floravol',
	'Cotovol',
	'Capumain',
	'Tournegrin',
	'Héliatronc',
	'Yanma',
	'Axoloto',
	'Maraiste',
	'Mentali',
	'Noctali',
	'Cornèbre',
	'Roigada',
	'Feuforêve',
	'Zarbi',
	'Qulbutoké',
	'Girafarig',
	'Pomdepik',
	'Foretress',
	'Insolourdo',
	'Scorplane',
	'Steelix',
	'Snubbull',
	'Granbull',
	'Qwilfish',
	'Cizayox',
	'Caratroc',
	'Scarhino',
	'Farfuret',
	'Teddiursa',
	'Ursaring',
	'Limagma',
	'Volcaropod',
	'Marcacrin',
	'Cochignon',
	'Corayon',
	'Rémoraid',
	'Octillery',
	'Cadoizo',
	'Démanta',
	'Airmure',
	'Malosse',
	'Démolosse',
	'Hyporoi',
	'Phanpy',
	'Donphan',
	'Porygon2',
	'Cerfrousse',
	'Queulorior',
	'Débugant',
	'Kapoera',
	'Lippouti',
	'Élekid',
	'Magby',
	'Écrémeuh',
	'Leuphorie',
	'Raikou',
	'Entei',
	'Suicune',
	'Embrylex',
	'Ymphect',
	'Tyranocif',
	'Lugia',
	'Ho-Oh',
	'Célébi',
	'Arcko',
	'Massko',
	'Jungko',
	'Poussifeu',
	'Galifeu',
	'Braségali',
	'Gobou',
	'Flobio',
	'Laggron',
	'Medhyèna',
	'Grahyèna',
	'Zigzaton',
	'Linéon',
	'Chenipotte',
	'Armulys',
	'Charmillon',
	'Blindalys',
	'Papinox',
	'Nénupiot',
	'Lombre',
	'Ludicolo',
	'Grainipiot',
	'Pifeuil',
	'Tengalice',
	'Nirondelle',
	'Hélédelle',
	'Goélise',
	'Bekipan',
	'Tarsal',
	'Kirlia',
	'Gardevoir',
	'Arakdo',
	'Maskadra',
	'Balignon',
	'Chapignon',
	'Parecool',
	'Vigoroth',
	'Monaflèmit',
	'Ningale',
	'Ninjask',
	'Munja',
	'Chuchmur',
	'Ramboum',
	'Brouhabam',
	'Makuhita',
	'Hariyama',
	'Azurill',
	'Tarinor',
	'Skitty',
	'Delcatty',
	'Ténéfix',
	'Mysdibule',
	'Galekid',
	'Galegon',
	'Galeking',
	'Méditikka',
	'Charmina',
	'Dynavolt',
	'Élecsprint',
	'Posipi',
	'Négapi',
	'Muciole',
	'Lumivole',
	'Rosélia',
	'Gloupti',
	'Avaltout',
	'Carvanha',
	'Sharpedo',
	'Wailmer',
	'Wailord',
	'Chamallot',
	'Camérupt',
	'Chartor',
	'Spoink',
	'Groret',
	'Spinda',
	'Kraknoix',
	'Vibraninf',
	'Libégon',
	'Cacnea',
	'Cacturne',
	'Tylton',
	'Altaria',
	'Mangriff',
	'Séviper',
	'Séléroc',
	'Solaroc',
	'Barloche',
	'Barbicha',
	'Écrapince',
	'Colhomard',
	'Balbuto',
	'Kaorine',
	'Lilia',
	'Vacilys',
	'Anorith',
	'Armaldo',
	'Barpau',
	'Milobellus',
	'Morphéo',
	'Kecleon',
	'Polichombr',
	'Branette',
	'Skélénox',
	'Téraclope',
	'Tropius',
	'Éoko',
	'Absol',
	'Okéoké',
	'Stalgamin',
	'Oniglali',
	'Obalie',
	'Phogleur',
	'Kaimorse',
	'Coquiperl',
	'Serpang',
	'Rosabyss',
	'Relicanth',
	'Lovdisc',
	'Draby',
	'Drackhaus',
	'Drattak',
	'Terhal',
	'Métang',
	'Métalosse',
	'Regirock',
	'Regice',
	'Registeel',
	'Latias',
	'Latios',
	'Kyogre',
	'Groudon',
	'Rayquaza',
	'Jirachi',
	'Deoxys',
];

const authorizeZone = {
	'bourg-palette': '0 Badge',
	'route-1': '0 Badge',
	'route-2': '0 Badge',
	'foret-de-jade': '0 Badge',
	'route-3': '1 Badge',
	'mont-selenite': '1 Badge',
	'route-4': '1 Badge',
	'route-24': '2 Badges',
	'route-25': '2 Badges',
	'route-5': '2 Badges',
	'route-6': '2 Badges',
	'cave-taupiqueur': '3 Badges',
	'route-9': '3 Badges',
	'route-10': '3 Badges',
	'route-11': '3 Badges',
	grotte: '3 Badges',
	lavanville: '3 Badges',
	'route-8': '3 Badges',
	'route-7': '3 Badges',
	'route-16': '4 Badges',
	'route-17': '4 Badges',
	'route-18': '4 Badges',
	'route-19': '5 Badges',
	'route-12': '5 Badges',
	'route-13': '5 Badges',
	'route-14': '5 Badges',
	'route-15': '5 Badges',
	dojo: '5 Badges',
	'parc-safari-n': '5 Badges',
	'parc-safari-s': '5 Badges',
	'parc-safari-e': '5 Badges',
	'parc-safari-o': '5 Badges',
	centrale: '5 Badges',
	'route-20': '6 Badges',
	'route-21': '6 Badges',
	'iles-ecume': '6 Badges',
	'manoir-pokemon': '7 Badges',
	'route-21': '7 Badges',
	'route-22': '8 Badges',
	'route-23': '8 Badges',
	'route-victoire': '8 Badges',
	'grotte-inconnue': '8 Badges',
	'bourg-geon': '0 Badge',
	'route-29': '0 Badge',
	'route-30': '0 Badge',
	'route-31': '0 Badge',
	'antre-noir': '0 Badge',
	'route-32': '1 Badge Gen2',
	'route-33': '1 Badge Gen2',
	'ruines-alpha': '1 Badge Gen2',
	'caves-jumelles': '1 Badge Gen2',
	'route-34': '2 Badges Gen2',
	'bois-au-chene': '2 Badges Gen2',
	'route-35': '3 Badges Gen2',
	'route-36': '3 Badges Gen2',
	'route-37': '3 Badges Gen2',
	'parc-naturel': '3 Badges Gen2',
	'route-38': '4 Badges Gen2',
	'route-39': '4 Badges Gen2',
	'tour-cendree': '4 Badges Gen2',
	'tour-ferraille': '4 Badges Gen2',
	'route-40': '5 Badges Gen2',
	'route-41': '5 Badges Gen2',
	'tourb-iles': '5 Badges Gen2',
	'route-42': '6 Badges Gen2',
	'mont-creuset': '6 Badges Gen2',
	'route-43': '7 Badges Gen2',
	'route-44': '7 Badges Gen2',
	'route-45': '8 Badges Gen2',
	'route-46': '8 Badges Gen2',
	'route-de-glace': '8 Badges Gen2',
	'mont-argente': '8 Badges Gen2',
	'bourg-en-vol': '0 Badge',
	'route-101': '0 Badge',
	'route-102': '0 Badge',
	'route-103': '0 Badge',
	'route-104': '0 Badge',
	'bois-clementi': '0 Badge',
	'route-116': '1 Badge Gen3',
	'grotte-granite': '1 Badge Gen3',
	'route-105': '2 Badges Gen3',
	'route-110': '2 Badges Gen3',
	'route-117': '2 Badges Gen3',
	'route-112': '3 Badges Gen3',
	'chemin-ardent': '3 Badges Gen3',
	'route-113': '3 Badges Gen3',
	'route-114': '4 Badges Gen3',
	'route-115': '4 Badges Gen3',
	'route-118': '4 Badges Gen3',
	'route-119': '5 Badges Gen3',
	'route-120': '5 Badges Gen3',
	desert: '5 Badges Gen3',
	'route-121': '6 Badges Gen3',
	'parc-safari': '6 Badges Gen3',
	'mont-memoria': '6 Badges Gen3',
	'route-126': '7 Badges Gen3',
	'route-128': '7 Badges Gen3',
	'grotte-origine': '7 Badges Gen3',
	'site-meteore': '7 Badges Gen3',
	'santier-sinuroc': '7 Badges Gen3',
	'grotte-trefonds': '8 Badges Gen3',
	'pilier-celeste': '8 Badges Gen3',
	'ile-du-sud': '8 Badges Gen3',
	'tombeau-antique': '8 Badges Gen3',
	'ile-aurore': '8 Badges Gen3',
};

export { commandsPokechat, balls, pokemons, authorizeZone };
